const ERROR_CODES = {
  NO_SUCH_USER: '1',
  INVALID_CREDENTIALS: '2',
  JWT: '3',
  REQUIRED_ROLES_NOT_PRESENT: '5',
  INTERNAL_SERVER_ERROR: '6',
  NOT_FOUND: '7',
  ALREADY_REGISTERED: '8',
  BAD_REQUEST: '9',
  VALIDATION_FAILED: '10',
  UNAUTHORIZED: '11',
};

export default ERROR_CODES;
