const EVENT_STATUS = {
  CANCELLED: 'CANCELLED',
  POSTPONED: 'POSTPONED',
  RESCHEDULED: 'RESCHEDULED',
  ACTIVE: 'ACTIVE',
  PASSED: 'PASSED',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  UNAPPROVED: 'UNAPPROVED',
  UNRECOGNIZED: 'UNRECOGNIZED',
};

export default EVENT_STATUS;
