const TRANSACTION_TYPE = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  EVENT_BUY: 'EVENT_BUY',
  EVENT_REFUND: 'EVENT_REFUND',
  UNRECOGNIZED: 'UNRECOGNIZED',
};

export default TRANSACTION_TYPE;
